### ISSUE TITLE
Json file with no data for segmentation !!

### ISSUE THREAD

**Issue by hahajaja** [zak-45/SCAnalyzer-Chataigne-Module#1]
![image](https://github.com/zak-45/SCAnalyzer-Chataigne-Module/assets/23209894/eb8bef48-df86-484f-91e9-dc7d0613da5d)

An error is reported after clicking the trigger

**Comment by kirill-deluxe** [comment]
hi, i have this trouble too...
773	Audio	Imported audio file is longer than the sequence, expanding total time to match the audio file length. - this message with any file 1,2,5min
and Json file with no data...
Help plz.
i install all versions, install manually and have a many crashes, then autoinstall pakg - have no crash, but still not work.
