### ISSUE TITLE
Crash Chataigne

### ISSUE THREAD

**Issue by Alexisp76** [zak-45/SCAnalyzer-Chataigne-Module#2]
Good morning,
I'm using Chestnut 1.9.19, with Sonoma 14.5. I installed everything requested in the documentation, however when I open the plugin, the Mac stalls and eventually crashes.
Is the module compatible with 1.9.19?
Thanking you in advance, 
Sincerely

**Comment by zak-45** [comment]
Hi, just tested on Windows with provided exe installer. Work but this is Chataigne 1.9.17. Some changes had probably made on the new Chataigne version. Can you test with the last one ( 1.9.17)?

**Comment by zak-45** [comment]
tested on 1.9.19. Not work 
![image](https://github.com/zak-45/SCAnalyzer-Chataigne-Module/assets/121941293/208d9bfd-523c-48a8-b998-6ffb8f08fe14)
Not really surprised cause Chataigne updates contains sometimes breaking changes. Put on TODO.

**Comment by Alexisp76** [comment]
Ok thanks for the quick feedback. Will it work on Mac with 1.9.17?

**Comment by zak-45** [comment]
Do not own Mac, so just try and let us know.
