### ISSUE TITLE
audio file is longer and empty json

### ISSUE THREAD

**Issue by kirill-deluxe** [zak-45/SCAnalyzer-Chataigne-Module#3]
hi, i have a trouble... 
773 Audio Imported audio file is longer than the sequence, expanding total time to match the audio file length. - this message with any file 1,2,5min
and Json file with no data...
Help plz.
i am install all versions of Chataigne, and install module manually (have a many crashes) then install SCAnalyzer.exe - have no crash, but still not work.
on 1.9.16x64 and 1.9.24x64 - the same problem too
Win11

**Comment by kirill-deluxe** [comment]
4:07:59	ModuleFactory	Found custom module : Custom:SCAnalyzer
4:07:59	ModuleFactory	Found custom module : Custom:SCAnalyzer_util
4:07:59	MIDI	Device In Added : TouchOSC Bridge
4:07:59	MIDI	Device In Added : VMidi 1
4:07:59	MIDI	Device In Added : VMidi 2
4:07:59	MIDI	Device In Added : VMidi 3
4:07:59	MIDI	Device In Added : VMidi 4
4:07:59	MIDI	Device Out Added : Microsoft GS Wavetable Synth
4:07:59	MIDI	Device Out Added : TouchOSC Bridge
4:07:59	MIDI	Device Out Added : VMidi 1
4:07:59	MIDI	Device Out Added : VMidi 2
4:07:59	MIDI	Device Out Added : VMidi 3
4:07:59	MIDI	Device Out Added : VMidi 4
4:07:59	Engine	Session loaded in 1.73448e+09s
4:07:59	CustomLoggerUI	Chataigne v1.9.24 : (08/10/24 (17:36))
4:08:00	AppUpdater	App is up to date :) (Latest version online : 1.9.24)
4:08:08	Script : SCAnalyzer	Script loaded succesfully
4:08:09	Script : SCAnalyzer_util	Script loaded succesfully
4:08:13	CommunityModuleManager	Finished fetching Community modules.
4:10:00	Audio	Imported audio file is longer than the sequence, expanding total time to match the audio file length.

**Comment by zak-45** [comment]
Hi, 
New versions of Chataigne sometimes break the rules.
This is why 1.9.24 do not work and you need, for the moment, to use the one provided into the exe file, v1.9.17.
'Audio Imported audio file is longer than the sequence' is only an information and is normal, so no problem on this way.
'and Json file with no data...' is more problematic, what you can try is to change some settings to see how this work.
see here more information : [segmenter](https://vamp-plugins.org/plugin-doc/qm-vamp-plugins.html#qm-segmenter)
If you could, provide a small file to me for test.

**Comment by kirill-deluxe** [comment]
Hi. I deleted everything today. plug-ins, programs, etc. then I installed your installer (first of all, it asked me to restart the system at the end - there was no such thing) I did everything - I rolled vamp2.0 from above - and a separately downloaded QM. after the start of the program, there was a warning about the wrong date format))) - I just changed "." to "/" and hooray!!! everything worked. Thank you for your attention and quick response.

**Comment by ArtykoRA** [comment]
Hello, I have same problem.... Sometimes...
I repeated step by step installation instructions.  W10 and .exe 1.1.0 from tags. and a separately downloaded QM.
I alternate three mistakes:  sometimes (the less) "json file no data.." , sometimes just do nothing. And most of the time create Sequence with audio but no triggers with this error:  11:42:14.489	SCAnalyzer	Script Error : Line 2695, column 49 : Unknown function 'replace'

I´m lost. Any idea, What I can do? 
Thanks

![Image](https://github.com/user-attachments/assets/fb5b2a68-e620-438d-b2f0-210de61abb45)

**Comment by zak-45** [comment]
Hi, plz open a new issue as this one is closed, thanks
